### ISSUE TITLE
Indsætte filnavn i referencer på tværs af tekster?

### ISSUE THREAD

**Issue by axgeertinger** [dsldk/salmer_data#4]
Henvisninger på tværs af teksterne er p.t. kodet som interne referencer, f.eks. i Vingaard:
```
<ref target="#sl-127">
   <orig>Den Cxxvii. Psal.</orig>
   <reg>Sl 127</reg>
</ref>
```
Der bør vel indsættes et filnavn, når henvisningen er til en anden tekst? Altså
`<ref target="christian-3-bibel.xml#sl-127"> [...]`

**Comment by axgeertinger** [comment]
Der er nu lavet en konkordansfil med id'er. De er unikke, så filnavnene behøves sådan set ikke. Jeg foreslår derfor at fortryde indsættelsen af "christian-3-bibel" foran @xml:id, da det ellers skal rettes til noget andet mange steder. 
Når det er fjernet, kan jeg rette de få steder, hvor der er problemer med id'erne (som skal rettes under alle omstændigheder).

**Comment by thsh77** [comment]
[ref_targets_list.txt](https://github.com/dsldk/salmer_data/files/4786459/ref_targets_list.txt)

**Comment by axgeertinger** [comment]
Klares vha. konkordansen. 
[concordance.zip](https://github.com/dsldk/salmer_data/files/5102273/concordance.zip)
